configfile: "config/config.yaml"

samples = config["samples"]
input_path = config["input_path"]
mates = ["1", "2"]

rule all:
    input:
        expand("results/fastqc/raw/{sample}_{mate}_fastqc.html",
               sample=samples, mate=mates),
        expand("results/fastqc/filtered/{sample}_{mate}_filtered_fastqc.html",
               sample=samples, mate=mates),       
        expand("results/fastp/{sample}_fastp.html", sample=samples),
        expand("results/hisat2/{sample}.sorted.bam.bai", sample=samples),
        expand("results/counts/{sample}.featureCounts.txt.summary", sample=samples),
        "results/multiqc/multiqc_report.html",
        "results/DEG/DEG_report.html" 

include: "rules/preprocess.smk"
include: "rules/alignment.smk"
include: "rules/counts.smk"
include: "rules/multiqc.smk"
include: "rules/deg.smk"

