configfile: "config/config.yaml"

samples = config["samples"]
input_path = config["input_path"]

rule all:
    input:
        expand("results/fastqc/{sample}_{stage}_fastqc.html", sample=samples, stage=["raw","filtered"]),
        expand("results/fastp/{sample}_fastp.html", sample=samples),
        expand("results/hisat2/{sample}.sorted.bam.bai", sample=samples),
        expand("results/counts/{sample}.featureCounts.txt.summary", sample=samples),
        "results/multiqc/multiqc_report.html",
        "results/DEG/DEG_report.html" 

include: "rules/preprocess.smk"
include: "rules/alignment.smk"
include: "rules/counts.smk"
include: "rules/multiqc.smk"
include: "rules/deg.smk"

